slam_toolbox:
  ros__parameters:
    # SLAM配置
    use_sim_time: false
    slam_mode: "mapping"  # mapping, localization, pure_localization
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 12.0  # 根据您的激光雷达调整

    # 优化器参数
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: HuberLoss

    # 回环检测
    enable_interactive_mode: false
    enable_detections: true
    max_loop_closures: 10
    loop_search_distance: 2.0
    loop_match_minimum_chain_size: 10
    max_correlative_expansion_search: 0.05
    minimum_travel_heading: 0.5
    minimum_travel_distance: 0.5
    
    # ROS 2相关参数
    transform_publish_period: 0.05
    map_publish_period: 1.0
    
    # 扫描匹配参数
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # 基本参数
    debug_logging: false
    throttle_scans: 1
    publish_occupancy_map: true
    max_range: 12.0  # 最大范围
    min_range: 0.15  # 最小范围
    max_z: 1.0  # 最大高度
    min_z: -1.0  # 最小高度
    
    # SLAM地图参数
    map_start_x: 0.5
    map_start_y: 0.5
    map_start_angle: 0.0 